# Generated by Django 4.0 on 2025-01-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kouka', '0002_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
    ]
