# Generated by Django 4.0 on 2025-01-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kouka', '0007_comment_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
