# Generated by Django 4.0 on 2025-01-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouka', '0008_remove_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.CharField(choices=[('general', '一般'), ('announcement', 'お知らせ'), ('question', '質問')], default='general', max_length=20, verbose_name='トピック'),
        ),
    ]
